## Attention mechanism in transformers

### Main idea:
    - 2 sequences(equals in case of self attention), A and B
    - let's see how much each element from A is related to each element from B
    - let's recombine A according to this
    
### Before:
    a given sequence A (and a context B).
### After:
    a new sequence where element i is a mix of elements from A that were related to element B(i)
    

### Dot product:
    mathematically, gives information about the similarity between 2 vectors

In [3]:
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    print('gpu', gpu)
    tf.config.experimental.set_memory_growth(gpu, True)
    print('memory growth:' , tf.config.experimental.get_memory_growth(gpu))
import numpy as np

gpu PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
memory growth: True


In [27]:
x = np.arange(10).reshape(1, 5, 2)
print(x)

y = np.arange(10, 20).reshape(1, 2, 5)
print(y)

[[[0 1]
  [2 3]
  [4 5]
  [6 7]
  [8 9]]]
[[[10 11 12 13 14]
  [15 16 17 18 19]]]


In [28]:
t = tf.keras.layers.Dot(axes=(1,2))([x,y])
print(t)

tf.Tensor(
[[[260 360]
  [320 445]]], shape=(1, 2, 2), dtype=int64)


In [50]:
a = tf.constant(np.array([[1, 2, 3], [2, 4, 6]]),dtype=tf.float32)
print(a.ndim)
    # A 3x2 matrix
b = tf.constant(np.array([[1, 10],[2, 20],[3, 30]]),dtype=tf.float32)
print(b.ndim)
    # Perform dot product
c = tf.matmul(a, b)

print(c)

2
2
tf.Tensor(
[[ 14. 140.]
 [ 28. 280.]], shape=(2, 2), dtype=float32)
